avatar_halos:
  type: objects
  default: []
  schema:
    name: avatar_halo_rule
    identifier: groups
    properties:
      groups:
        type: groups
        disallowed_groups: "0|4|5" # disallow groups `everyone`, `anonymous users`, `logged-in users` 
        required: true
      halo_color:
        type: string
        required: true
        validations:
          min_length: 3
      halo_size:
        type: enum
        choices:
          - small
          - medium
          - large         
      halo_transparency:
        type: enum
        choices:
          - "0.25"
          - "0.5"
          - "0.75"
          - "1.0"
